services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ~/prod-grade-flow/frontend:/app

  frontend_tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ~/prod-grade-flow/frontend:/app
    command: ["npm", "run", "test"]
    