name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jeldikk/prod-frontend -f Dockerfile.dev .
      - run: docker run -e CI=true jeldikk/prod-frontend npm test -- --coverage

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElastiBeanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: prod-frontend
          environment_name: Prod-frontend-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-339712998487
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip